services:

  mysql-db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  spring-app:
    image: lab_10:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/ASD?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test1234

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  mysql-data:
    driver: local
