services:

  mysql-db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ASD
      MYSQL_ROOT_PASSWORD: test1234
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build:
      context: .
    ports:
      - "8080:8080"
volumes:
  mysql-data:
    driver: local
